platform:ios,’8.0’
pod 'SDWebImage','~>3.7.3'
pod 'AFNetworking', '~> 3.1.0'
pod 'SVProgressHUD','~> 1.1.3'
pod 'MJExtension', '~> 2.5.6'
pod 'MJRefresh', '~> 2.4.5'
pod 'JSONModel', '~> 1.1.0'
pod 'Reachability', '~> 3.2'
pod 'JSONKit-NoWarning', '~> 1.2'
pod 'FMDB', '~> 2.6.2’
pod 'JSONKit-NoWarning', '~> 1.2'
pod 'UMengAnalytics', '~> 4.0.4'
pod 'UMengSocialCOM', '~> 5.2.1’
pod 'ZYQAssetPickerController', '~> 1.0.0'